version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet

    steps:
      - checkout

      - run:
          name: Build
          command: dotnet build

      - run:
          name: Test
          command: dotnet test